from __future__ import annotations

import warnings
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP
from pydantic_settings.exceptions import IncompleteFieldDefinitionWarning

from .service import AnalysisResult, analyze_source, safe_name, write_analysis
from .source import normalize_arxiv_url


ARTIFACTS = {
    "paper.html": ("html", "text/html"),
    "paper.md": ("markdown", "text/markdown"),
    "paper.json": ("json", "application/json"),
}


def _artifact_uri(paper_key: str, filename: str) -> str:
    return f"rpl://papers/{paper_key}/{filename}"


def _artifact_summary(paths: list[Path], paper_key: str) -> list[dict[str, str]]:
    artifacts: list[dict[str, str]] = []
    for path in paths:
        output_format, mime_type = ARTIFACTS[path.name]
        artifacts.append(
            {
                "format": output_format,
                "path": str(path),
                "file_uri": path.as_uri(),
                "resource_uri": _artifact_uri(paper_key, path.name),
                "mime_type": mime_type,
            }
        )
    return artifacts


def analyze_for_mcp(
    source: str, *, output_root: str | Path, timeout: float = 30.0
) -> dict[str, Any]:
    """Run RPL and return a compact result suitable for an MCP tool call."""

    normalize_arxiv_url(source)
    analysis: AnalysisResult = analyze_source(source, timeout=timeout)
    paths = write_analysis(analysis, output_root)
    paper_key = safe_name(analysis.paper.paper_id)
    return {
        "status": "completed",
        "paper": {
            "paper_id": analysis.paper.paper_id,
            "title": analysis.paper.title,
            "authors": analysis.paper.authors,
            "published": analysis.paper.published,
            "source_url": analysis.paper.source_url,
            "paper_type": analysis.digest.paper_type,
            "paper_type_confidence": analysis.digest.paper_type_confidence,
        },
        "digest": analysis.digest.to_dict(),
        "comparison": analysis.comparison.to_dict(),
        "artifacts": _artifact_summary(paths, paper_key),
    }


def create_server(
    output_root: str | Path | None = None, *, timeout: float = 30.0
) -> FastMCP:
    """Create a local RPL MCP server with isolated, configurable storage."""

    root = Path(output_root or Path.home() / "RPL").expanduser().resolve()
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            message="Field 'lifespan' has an incomplete definition.*",
            category=IncompleteFieldDefinitionWarning,
        )
        server = FastMCP(
            "RPL",
            instructions=(
                "Use RPL to turn an arXiv URL or identifier into a grounded paper "
                "guide. Return the HTML artifact to the user when available."
            ),
            log_level="WARNING",
        )

    @server.tool(
        name="analyze_arxiv_paper",
        description=(
            "Analyze one arXiv paper and create local HTML, Markdown, and JSON "
            "artifacts. The result includes exact local paths and MCP resource URIs."
        ),
    )
    def analyze_arxiv_paper(source: str) -> dict[str, Any]:
        return analyze_for_mcp(source, output_root=root, timeout=timeout)

    def read_artifact(paper_key: str, filename: str) -> str:
        if safe_name(paper_key) != paper_key or filename not in ARTIFACTS:
            raise ValueError("Unknown RPL artifact.")
        path = root / paper_key / filename
        try:
            return path.read_text(encoding="utf-8")
        except OSError as exc:
            raise ValueError(f"Could not read RPL artifact: {exc}") from exc

    @server.resource(
        "rpl://papers/{paper_key}/paper.html",
        name="RPL HTML paper guide",
        description="The standalone visual paper guide generated by RPL.",
        mime_type="text/html",
    )
    def paper_html(paper_key: str) -> str:
        return read_artifact(paper_key, "paper.html")

    @server.resource(
        "rpl://papers/{paper_key}/paper.md",
        name="RPL Markdown paper guide",
        description="The Markdown learning card generated by RPL.",
        mime_type="text/markdown",
    )
    def paper_markdown(paper_key: str) -> str:
        return read_artifact(paper_key, "paper.md")

    @server.resource(
        "rpl://papers/{paper_key}/paper.json",
        name="RPL structured paper data",
        description="The structured paper and comparison data generated by RPL.",
        mime_type="application/json",
    )
    def paper_json(paper_key: str) -> str:
        return read_artifact(paper_key, "paper.json")

    return server


def run_server(output_root: str | Path | None = None, *, timeout: float = 30.0) -> None:
    """Run the local server over stdio for an MCP host to launch."""

    create_server(output_root, timeout=timeout).run(transport="stdio")
